### ISSUE TITLE
Clear Requirement for Reii-Yuki-Site 2.0

### ISSUE THREAD

**Issue by ReiiYuki** [ReiiYuki/Reii-Yuki-Site#1]
Clear the requirement for Reii-Yuki-Site 2.0

#### Todo :
- [x] Clear Use case
- [ ] Design Database
- [ ] Cloud Function Design
- [ ] UI Design
- [ ] Develop on Admin UI
- [ ] Develop on Site
